#!/usr/bin/env bash

year=$(date +%Y)

if [ "$1" = "" ]; then
	echo "Usage: $0 SLUG"
	echo "    -> content/blog/${year}/SLUG.md"
	exit
fi

slug="$1"
dtx=$(date +%Y-%m-%dT%H:%M:%SZ)
base_dir="$(dirname $0)/.."
fname="${base_dir}/content/blog/${year}/${slug}.md"

[ -e "$fname" ] && {
	echo "File ${fname} exists."
	exit 1
}

[ ! -d $(dirname "${fname}") ] && {
  mkdir -p $(dirname "${fname}") > /dev/null 2>&1
}

cat <<EOF > $fname
+++
draft = false
title = "$slug"
date = $dtx
+++

EOF

echo "Created: ${fname}" | sed 's,^\(Created:\).*\(content/blog/.*\)$,\1 \2,'
EDITOR=${EDITOR:-vim}
exec $EDITOR $(readlink -f ${fname})

