#!/usr/bin/env bash

year=$(date +%Y)

if [ "$2" = "" ]; then
	echo "Usage: $0 TAG SLUG"
	exit
fi

tagname="$1"
slug="$2"
dtx=$(date +%Y-%m-%dT%H:%M:%SZ)
base_dir="$(dirname $0)/.."
fname="${base_dir}/content/til/${tagname}/${slug}.md"

[ -e "${fname}" ] && {
	echo "File ${fname} exists."
	exit 1
}

[ ! -d $(dirname "${fname}") ] && {
  mkdir -p $(dirname "${fname}") > /dev/null 2>&1
}

cat <<EOF > $fname
+++
draft = false
title = "$slug"
date = $dtx
tags = ["$tagname"]
+++

EOF

echo "Created: ${fname}" | sed 's,^\(Created:\).*\(content/til/.*\)$,\1 \2,'
EDITOR=${EDITOR:-vim}
exec $EDITOR $(readlink -f ${fname})
